---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: NAMESPACE
  labels:
    app: redisnw
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redisnw
    role: master
    tier: backend

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  labels:
    app: redis-master-monitor-svc
    k8s-app: redis
  name: redis-master-monitor-svc
  namespace: NAMESPACE
spec:
  ports:
  - name: redis-metrics
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: redisnw
  sessionAffinity: None
  type: ClusterIP