---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: NAMESPACE
  labels:
    app: redisnw
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redisnw
    role: slave
    tier: backend