---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: APPLICATIONNAME
  labels:
    app: APPLICATIONNAME
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPLICATIONNAME
  template:
    metadata:
      name: APPLICATIONNAME
      labels:
        app: APPLICATIONNAME
    spec:
      containers:
      - name: APPLICATIONNAME
        image: us.gcr.io/just-slate-88918/APPLICATIONNAME:BUILDVERSION
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: ENVIRONMENTNAMEUPPER
        - name: TZ
          value: COUNTRY/STATE
        resources:
          limits:
            cpu: "VCPUMAX"
            memory: VMEMORYMAX
          requests:
            cpu: VCPUMIN
            memory: VMEMORYMIN
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: APPPNUMBER
          timeoutSeconds: 1
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
      - name: nginx-vts-exporter
        image: us.gcr.io/just-slate-88918/nginx-vts-exporter:v0.10.3
        ports:
        - containerPort: 9913
          name: port9913
          protocol: TCP