---
apiVersion: v1
kind: Service
metadata:
  name: APPLICATIONNAME
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: APPLICATIONNAME
spec:
  type: LoadBalancer
  loadBalancerIP: INTERNALLBIP
  loadBalancerSourceRanges: 
    - 10.0.0.0/8
  ports:
  - name: tcp-PORT-APPPNUMBER-APPLICATIONNAME
    port: PORT
    protocol: TCP
    targetPort: APPPNUMBER
  selector:
    app: APPLICATIONNAME