---
apiVersion: v1
kind: Service
metadata:
  name: APPLICATIONNAME
  namespace: qa3
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: APPLICATIONNAME
spec:
  type: LoadBalancer
  loadBalancerIP: 10.105.36.70 
  loadBalancerSourceRanges: 
    - 10.0.0.0/8
    - 10.105.36.64/27 
    - 10.105.36.0/26
    - 10.105.32.0/22
    - 10.105.0.0/19
  ports:
  - name: tcp-80-80-APPLICATIONNAME
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: APPLICATIONNAME