---
- name: Ensure apache is installed and started
  hosts: webservers
  become: yes
  remote_user: devops_practiceworks2019
  tasks:
  - name: Ensure httpd package is present
    yum:
      name: httpd
      state: present

  - name: Ensure latest index.html file is present
    copy:
      src: index.html
      dest: /var/www/html/

  - name: Ensure httpd is started
    service:
      name: httpd
      state: started
