---
kind: Service
apiVersion: v1
metadata:
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  name: APPLICATIONNAME
  namespace: NAMESPACE
  labels:
    app: APPLICATIONNAME
spec:
  ports:
  - name: tcp-PORT-APPPNUMBER-APPLICATIONNAME
    protocol: TCP
    port: PORT
    targetPort: APPPNUMBER
  selector:
    app: APPLICATIONNAME
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  loadBalancerIP: INTERNALLBIP 
  loadBalancerSourceRanges: 
    - 10.0.0.0/8
