---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: APPLICATIONNAME
  namespace: NAMESPACE
  labels:
    app: APPLICATIONNAME
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPLICATIONNAME
  template:
    metadata:
      name: APPLICATIONNAME
      labels:
        app: APPLICATIONNAME
    spec:
      containers:
      - name: APPLICATIONNAME
        image: us.gcr.io/just-slate-88918/APPLICATIONNAME:BUILDVERSION