        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: APPPNUMBER
            scheme: HTTP
          initialDelaySeconds: LIVENESSPROBEDELAY
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2