---
apiVersion: v1
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: NAMESPACE-endpoint-reader
  namespace: NAMESPACE
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]

---