---
apiVersion: v1
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: NAMESPACE-endpoint-reader
  namespace: NAMESPACE
subjects:
- kind: ServiceAccount
  name: rabbitmqNAMESPACEsvc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: NAMESPACE-endpoint-reader
---