---
apiVersion: v1
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-admin-binding-NAMESPACE
  namespace: NAMESPACE
subjects:
- kind: User
  name: SERVICEACCOUNT
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""