apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-k8s
  namespace: jenkins
  labels:
    failure-domain.beta.kubernetes.io/region: "us-central1" 
    failure-domain.beta.kubernetes.io/zone: "us-central1-c" 
spec:
  storageClassName: ssd
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: jenkins-master-k8s
    fsType: ext4